### PR TITLE
User Management Page holder #2

### PR DESCRIPTION
**Pull request by KeerthanaReddyMogulla**
A new MyComponent login form with username and password fields is integrated as part of this pull request and can be accessed from the /mycomponent navigation menu. Other routes were modified for consistent navigation, and the app structure in App.js was modified to accommodate routing for this new component. Custom colors, font sizes, and spacing were introduced in tailwind.config.js to maintain a consistent style, and Tailwind CSS was heavily utilized for styling. To make the project better organized.Gitignore was modified to remove unnecessary files and node_modules from version control. To improve readability and maintainability, the JSX code structure was also made simpler across all components. To guarantee alignment with the main branch, all changes were staged, committed, and pushed when merge conflicts were settled. This version was checked to make sure the user interface is responsive on various screen sizes, all routes operate as intended, and the login form validation is functioning properly. The integration, styling, and structural enhancements needed for this component are finished with this pull request.

### CODE REVIEW

**Comment by davidlislc** [comment]
Can you try to reduce the conflicts?

**Comment by davidlislc** [comment]
We have a login form that can do the real login. Can you integrate that code with yours?

**Comment by KeerthanaReddyMogulla** [comment]
> We have a login form that can do the real login. Can you integrate that code with yours?

I have integrated my login page with the login form.

**Comment by davidlislc** [comment]
Make sure you use the develop branch as your base, try to limit modified file under 5.

**Pull request closed without merging**
