### PR TITLE
Batch Job

### PR DESCRIPTION
**Pull request by AnilKumarCh12**
Completed the batch job list as required

### CODE REVIEW

**Comment by davidlislc** [comment]
please see the comments, and fix them. I will help you guys out if you stuck.

**Comment by AnilKumarCh12** [comment]
what are the things we need to fix

**Comment by AnilKumarCh12** [comment]
we are stuck with errors when we try to post jobs while using create job page. we can't able to post to api. How to post to api

**Comment by davidlislc** [comment]
Please refer to the tutorial for instructions.
Please provide the story in the title, please provide the url in the description. Also please include this PR url in your story comment area. Let me know once you are done.
You run out time, I will merge the code once I hear from you.

**Pull request closed without merging**
