### PR TITLE
Scrum 1

### PR DESCRIPTION
**Pull request by ajayavula682**
pushed my code to  scrum-1 branch

### CODE REVIEW

**Comment by davidlislc** [comment]
We will talk about it in class if this is a Wed team story

**Comment by ajayavula682** [comment]
added files from subscription folder to admin folder

**Comment by davidlislc** [comment]
Can you fix all the confilcits?

**Comment by ajayavula682** [comment]
I will start working on to fix the pr porfessor

**Comment by davidlislc** [comment]
there are conflicts

**Comment by ajayavula682** [comment]
I will solve the conflicts

**Pull request closed without merging**
