### PR TITLE
Kay01

### PR DESCRIPTION
**Pull request by skommineni05**
Complete UI changes for all pages done. Sample UI implemented in all pages except for login page. Need to work on login UI.

### CODE REVIEW

**Comment by davidlislc** [comment]
Can you check if it is necessary to change so many files?

**Comment by skommineni05** [comment]
yes professor. Added UI to all those files no API or any java script changes.

**Comment by davidlislc** [comment]
Can you update the pr so no conflicts? I know I pulled you into the header and navigation team, if you want to discontinue this effort, It is ok too.

**Comment by davidlislc** [comment]
there are conflicts

**Pull request closed without merging**
