### PR TITLE
PC - 37 User list API call: All users list

### PR DESCRIPTION
**Pull request by KeerthanaReddyMogulla**
This pull request enhances the User Role Page by introducing dynamic dashboards for Admin, Editor, and Viewer roles with role-based redirection and access management. The Admin dashboard now displays a user list fetched from the backend API with proper authentication, while Editor and Viewer roles have tailored navigation to their specific dashboards.

### CODE REVIEW

**Comment by davidlislc** [comment]
Which story is this? Can you edit the title to reflect it?

**Comment by KeerthanaReddyMogulla** [comment]
> Which story is this? Can you edit the title to reflect it?

User list API call: All users list.

**Comment by davidlislc** [comment]
Can you give the story number and update the jira ticket? I have no way to tell the story url

**Comment by KeerthanaReddyMogulla** [comment]
Hello professor. My story number is PC-37 User list API call: All users list. This is my jira story link. 
 https://indianatech-team-d3mlgy6s.atlassian.net/browse/PC-37?atlOrigin=eyJpIjoiMTgwNGE1MTdkYzQ1NDEzYmJmZDUzNjk4YzdjNzVjYzMiLCJwIjoiaiJ9

**Comment by davidlislc** [comment]
I added your changes and kept the old changes. I will add another route to test out.

**Pull request merged**
